In [5]:
@doc sin

```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
 0.454649  0.454649
 0.454649  0.454649
```


In [6]:
2 * 2

4

In [7]:
abs(-4)

4

In [8]:
sqrt(16)

4.0

In [9]:
√16 

4.0

In [10]:
exp(0)

1.0

In [11]:
log(e)

LoadError: UndefVarError: e not defined

In [12]:
log(ℯ)

1

In [13]:
factorial(1,2)

LoadError: MethodError: no method matching factorial(::Int64, ::Int64)
Closest candidates are:
  factorial(::Union{Int64, UInt64}) at combinatorics.jl:27
  factorial(::Integer) at intfuncs.jl:889

In [14]:
factorial(3)

6

In [15]:
@doc factorial

```
factorial(n::Integer)
```

Factorial of `n`. If `n` is an [`Integer`](@ref), the factorial is computed as an integer (promoted to at least 64 bits). Note that this may overflow if `n` is not small, but you can use `factorial(big(n))` to compute the result exactly in arbitrary precision.

# Examples

```jldoctest
julia> factorial(6)
720

julia> factorial(21)
ERROR: OverflowError: 21 is too large to look up in the table; consider using `factorial(big(21))` instead
Stacktrace:
[...]

julia> factorial(big(21))
51090942171709440000
```

# See also

  * [`binomial`](@ref)

# External links

  * [Factorial](https://en.wikipedia.org/wiki/Factorial) on Wikipedia.


In [16]:
binomial(7, 5)

21

In [17]:
im

im

In [18]:
2im+3 - im

3 + 1im

In [19]:
pi+2

5.141592653589793

In [20]:
Inf

Inf

In [21]:
ans

Inf

In [22]:
@doc ans

```
ans
```

A variable referring to the last computed value, automatically set at the interactive prompt.


# ZADANIE 1

In [23]:
3< pi <3.2

true

In [24]:
x = 17
3*x+2 == 53 && x^2 < 300

true

In [25]:
floor(log(29))

3.0

In [26]:
ℯ^(5//3*im*π)

0.5000000000000001 - 0.8660254037844386im

In [27]:
asin(sin(15//4*π))

-0.7853981633974496

In [67]:
√Complex((√(2)-2))

LoadError: DomainError with -0.5857864376269049:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [29]:
binomial(20,15)

15504

In [30]:
factorial(big(40))

815915283247897734345611269596115894272000000000

In [75]:
w1(x)=x^3+4x^2+7x+2

for i ∈ [0, 1//2, 11//10, tan(0.3), 2-im]
    println(w1(i),"\t\t", typeof(w1(i)))
end

2.0 + 0.0im		Complex{Float64}
6.625 + 0.0im		Complex{Float64}
15.871000000000002 + 0.0im		Complex{Float64}
4.577709458752641 + 0.0im		Complex{Float64}
30.0 - 34.0im		Complex{Float64}


# ZADANIE 2

In [32]:
ζ(z,N)= sum((1/i)^z for i in 1:N)
M=10000
for z ∈ [2,3,5.5]
    println(ζ(z, M))
end

1.6448340718480652
1.202056898160098
1.0252045799546707


In [33]:
prod((1+(1/2)^(2^i)) for i in 0:10000)

Inf

In [76]:
sum(sum(k for k in j:100) for j in 1:100)

338350

In [77]:
N = 10000000
dx = pi/N
sum(sin(dx*i)*dx for i in 0:N-1)

1.9999999999999394

# <font color='green'>ZADANIE 3</font>

In [36]:
A = [1 2; 3 4]
B = [im 1+2im; 2-im 0]
C = [1 2; 3 4; 5 6]
v = [1 1]
w2 = [1//2; 3//4]
z = [2.0, 0.0]
c = -1

-1

In [37]:
w2

2-element Array{Rational{Int64},1}:
 1//2
 3//4

In [38]:
A+B

2×2 Array{Complex{Int64},2}:
 1+1im  3+2im
 5-1im  4+0im

In [39]:
A .+ B

2×2 Array{Complex{Int64},2}:
 1+1im  3+2im
 5-1im  4+0im

In [40]:
A + c

LoadError: MethodError: no method matching +(::Array{Int64,2}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  +(::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  +(::Complex{Bool}, ::Real) at complex.jl:301
  ...

In [41]:
A .+ c

2×2 Array{Int64,2}:
 0  1
 2  3

In [42]:
A .* w2

2×2 Array{Rational{Int64},2}:
 1//2  1//1
 9//4  3//1

In [43]:
A * w2

2-element Array{Rational{Int64},1}:
 2//1
 9//2

In [44]:
exp(A)

2×2 Array{Float64,2}:
  51.969   74.7366
 112.105  164.074

In [45]:
exp.(A)

2×2 Array{Float64,2}:
  2.71828   7.38906
 20.0855   54.5982

In [46]:
zA^(-1)*B

LoadError: UndefVarError: zA not defined

In [47]:
using LinearAlgebra
dot(v, w2')

5//4

In [48]:
v*A'*w2

1-element Array{Rational{Int64},1}:
 27//4

In [49]:
cosh.(A)

2×2 Array{Float64,2}:
  1.54308   3.7622
 10.0677   27.3082

In [50]:
A.^2 .+c

2×2 Array{Int64,2}:
 0   3
 8  15

In [51]:
v'.+z'

2×2 Array{Float64,2}:
 3.0  1.0
 3.0  1.0

# ZADANIE 4

In [52]:
A = [1 2 -1 ; 1 1 1 ; 2 -1 2]
B = [1 2 1]'
Float64.(Rational.(A)\B)

3×1 Array{Float64,2}:
 0.0
 1.0
 1.0

# ZADANIE 5

In [53]:
ranK = -20:1:10
a_k = [2.0^k for k ∈ ranK]

31-element Array{Float64,1}:
    9.5367431640625e-7
    1.9073486328125e-6
    3.814697265625e-6
    7.62939453125e-6
    1.52587890625e-5
    3.0517578125e-5
    6.103515625e-5
    0.0001220703125
    0.000244140625
    0.00048828125
    0.0009765625
    0.001953125
    0.00390625
    ⋮
    0.5
    1.0
    2.0
    4.0
    8.0
   16.0
   32.0
   64.0
  128.0
  256.0
  512.0
 1024.0

In [54]:
N = 1000
ranL = 1: 2: N
sum(1/factorial(big(l)) for l in ranL)

1.175201193643801456882381850595600815155717981334095870229565413013307567304335

In [1]:
rng = LinRange(0, 5, 10000)
val = map(x -> x*log(x), rng[2:end])
minimum(val)

-0.3678794075198892

In [5]:
den = 1000
rg = LinRange(-1,1,den)
pts = [[(a,b) for a in rg] for b in rg]
cnt = 0

@time for p in pts
    for t in p
        if t[1]^2+t[2]^2<=1
            cnt+=1
        end
    end
end
print(cnt/den^2 *4)

 79.138053 seconds (873.44 M allocations: 15.996 GiB, 3.40% gc time)
3.1409544

ale szybciej można:

In [20]:
N = 10000
q = LinRange(-1.0,1.0, N)
@time count(q.^2 .+q'.^2 .<=1.0)*4/N^2

  0.174495 seconds (23 allocations: 11.926 MiB)


3.1409544

# ZADANIE 6 

In [32]:
function fun1()
    counter = 0
    times = 1000
    for i in 1:times
        a = 0
        for i in 1:3
            a += (rand([1,2,3,4])+1)
        end
        if a >= 7
            counter += 1
        end
    end
    print(counter/times)
end
@time fun1()

0.988  0.000264 seconds (3.01 k allocations: 328.750 KiB)


In [33]:
N = 1000000
@time count([sum(rand([1,2,3,4].+1,3))>=7 for _ in 1:N])/N

  0.350990 seconds (3.21 M allocations: 332.416 MiB, 11.91% gc time)


0.984412

In [28]:
counter = 0
times = 1000
for i in 1:times
    arr = [0, 0, 0]
    for i in 1:3
        arr[i] = (rand([1,2,3,4])+1)
    end
    arr = sort(arr)
    a = pop!(arr)
    if a>=5 && sum(arr)>=5
        counter += 1
    end
end
print(counter/times)

0.53

In [45]:
a = sort(rand([1,2,3,4].+1,3))

4

In [1]:


@time begin
    counter = 0
    times = 100000
    for i in 1:times
        magHP = 12
        skelHP = 13
        win = ""
        while true
            magHP -= ((rand([1,2,3,4,5,6]))+2)
            a = 0
            if magHP<=0
                win = false
                break
            end
            for i in 1:3
                a += (rand([1,2,3,4])+1)
            end
            skelHP -= a
            if skelHP<=0
                win = true
                break
            end
        end
        if win == true
            counter += 1
        end
    end
    print(counter/times)
end


0.64952  0.129134 seconds (1.11 M allocations: 83.903 MiB, 18.12% gc time)


In [1]:
N = 100000
Z= 3
@time count(sum(rand([1,2,3,4,5,6].+2) for _ in 1:(1+count(i < 13 for i in 
                        sum.(([sum(rand([1,2,3,4].+1,3)) for _ in 1:Z])[1:i] for i in 1:Z)))) < 12 for _ in 1:N)/N

  0.966750 seconds (6.86 M allocations: 531.112 MiB, 9.75% gc time)


0.64852

In [3]:
N = 1000
Z= 3
@time count(sum(rand([1,2,3,4,5,6].+2) for _ in 1:(1+count(i < 13 for i in 
                        cumsum(([sum(rand([1,2,3,4].+1,3)) for _ in 1:Z]))))) < 12 for _ in 1:N)/N

  0.283281 seconds (746.66 k allocations: 40.123 MiB, 3.56% gc time)


0.66